version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: content_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - webapi_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USER_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - webapi_network
    restart: unless-stopped
    depends_on:
      - postgres
  

  car-api1:
    build: ../src/
    image: car-api:latest
    container_name: gordo-cms-api
    environment:
      - PORT=9000
    ports:
      - 9000:5000
    networks:
      - webapi_network
    volumes:
      - logs:/app/logs
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
  logs:
networks:
  webapi_network:
    driver: bridge